version: "3.7"

services:
  react:
    container_name: react
    build:
      context: ./.
      dockerfile: Dockerfile
    volumes:
      - "./react/src:/app/src"
      - "/app/node_modules"
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
    networks:
      - network
networks:
  network:
    driver: bridge